### PR TITLE
19 breaking up scss file

### PR DESCRIPTION
**Pull request by dylanvu**
* break up scss to try to mimic the current file directory

ideally we have a way to test this out before we push to prod

### CODE REVIEW

**Comment by leavenember** [comment]
Is there a reason why the component scss files are not in the ./scss folder?

This can be tested in the preview branch. Feel free to merge main into preview first if you think it's necessary

**Comment by bcbielecki** [comment]
> Is there a reason why the component scss files are not in the ./scss folder?

I have a similar question. What is your justification/reasoning for placing some of the .scss files in the js folder @vu-dylan ?

**Comment by vu-dylan** [comment]
@leavenember @bcbielecki I put the components inside of the `js` directory to match our directory

**Comment by bcbielecki** [comment]
@vu-dylan Ooh okay, I may not still fully understand this. Do you have time after the Monday standup to explain it to me?

**Comment by leavenember** [comment]
> @vu-dylan Ooh okay, I may not still fully understand this. Do you have time after the Monday standup to explain it to me?

I think it's that the scss directory structure matches the HTML.

**Comment by vu-dylan** [comment]
yea the intention is to have the scss directory match the project directory, but I should have time after standup to explain more

**Review by bcbielecki — APPROVED** [review]
: )

**Pull request merged**
